"""add completion_notification_sent to approval_requests

Revision ID: 898092db231d
Revises: 1b509f6f8242
Create Date: 2025-08-14 19:52:06.544103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898092db231d'
down_revision: Union[str, Sequence[str], None] = '1b509f6f8242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_recipients', sa.Column('last_reminder_sent', sa.DateTime(), nullable=True))
    op.add_column('approval_requests', sa.Column('completion_notification_sent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_requests', 'completion_notification_sent')
    op.drop_column('approval_recipients', 'last_reminder_sent')
    # ### end Alembic commands ###
