"""Add document fields for upload

Revision ID: b5501eb977e2
Revises: 51f8f209781e
Create Date: 2025-08-09 12:47:23.363232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5501eb977e2'
down_revision: Union[str, Sequence[str], None] = '51f8f209781e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'file_hash')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
